#!/bin/sh
if test -f /etc/oss.conf
then
	. /etc/oss.conf
else
	OSSLIBDIR=/usr/lib/oss
fi

if ! test -d /proc
then
	echo soundon script requires procfs to be mounted at /proc!
	exit 200
fi

if test -f /proc/opensound/devfiles
then
	echo OSS is already loaded.
	exit 0
fi

NOTIFY=0

echo "Open Sound System starting" `date`
echo "OSS version: " `cat $OSSLIBDIR/version.dat`
KERNEL_VERSION=`uname -r`
echo "Kernel version: " $KERNEL_VERSION

if ! test -f $OSSLIBDIR/etc/installed_drivers
then
	echo No $OSSLIBDIR/etc/installed_drivers - running ossdetect
	/usr/sbin/ossdetect -v
fi

if ! test -f $OSSLIBDIR/etc/installed_drivers
then
	echo Still no $OSSLIBDIR/etc/installed_drivers - cannot continue
	echo No $OSSLIBDIR/etc/installed_drivers - cannot continue
	exit 10
fi

OSSCOREKO="/lib/modules/$KERNEL_VERSION/kernel/sound/oss/osscore.ko"
if ! test -f ${OSSCOREKO}
then
	echo No ${OSSCOREKO} module in the system
	exit 30
fi

if test -f $OSSLIBDIR/etc/license.asc
then
	/usr/sbin/ossdetect -l
fi

if ! test -f /proc/opensound/devfiles
then
	echo OSS Core module not started
	dmesg
	exit 70
fi

/usr/sbin/ossdetect -d
/usr/sbin/ossdevlinks -v

echo "+++ ossinfo -v3 +++"
ossinfo -v3
echo "+++ /dev/sndstat +++"
cat /dev/sndstat
echo "+++ /proc/opensound/devfiles +++"
cat /proc/opensound/devfiles
ls -l /dev/dsp* /dev/mixer* /dev/midi* /dev/oss/*/*

/usr/sbin/savemixer -L -v


if test -x $OSSLIBDIR/soundon.user
then
	echo Running $OSSLIBDIR/soundon.user
	$OSSLIBDIR/soundon.user
fi

# Use alternative place for soundon.user
if test -x /etc/oss/soundon.user
then
	echo Running /etc/oss/soundon.user
	/etc/oss/soundon.user
fi

if test "`ossinfo -g|grep TRIAL` " != " "
then
	echo
	echo "************************************************************"
	echo "* NOTE! You are using trial version of Open Sound System   *"
	echo "************************************************************"
	echo

	sleep 1
fi

if test "`ossinfo -g|grep EXPIRED` " != " "
then
	echo
	echo "****************************************************************"
	echo "* NOTE! Your Open Sound System evaluation license has expired  *"
	echo "****************************************************************"
	echo

	sleep 15
fi

if test "$NOTIFY " = "1 "
then
	echo OSS started OK
fi

exit 0
